### ISSUE TITLE
1.22.0 build failing, 1.21.0 build ok, Systemd problem?

### ISSUE THREAD

**Issue by jmrcpn** [mate-desktop/mate-session-manager#198]
Unable to successfully build on 1.22.0 (systemd problem?)
/usr/lib64/gcc/x86_64-ok-linux-gnu/8.3.0/../../../../x86_64-ok-linux-gnu/bin/ld: mate_session-gsm-systemd.o: in function `gsm_systemd_is_last_session_for_user':
/home/jmp/rpmbuild/BUILD/mate-session-manager-1.22.0/mate-session/gsm-systemd.c:432: undefined reference to `sd_pid_get_session'
/usr/lib64/gcc/x86_64-ok-linux-gnu/8.3.0/../../../../x86_64-ok-linux-gnu/bin/ld: /home/jmp/rpmbuild/BUILD/mate-session-manager-1.22.0/mate-session/gsm-systemd.c:438: undefined reference to `sd_uid_get_sessions'
/usr/lib64/gcc/x86_64-ok-linux-gnu/8.3.0/../../../../x86_64-ok-linux-gnu/bin/ld: /home/jmp/rpmbuild/BUILD/mate-session-manager-1.22.0/mate-session/gsm-systemd.c:453: undefined reference to `sd_session_get_state'
/usr/lib64/gcc/x86_64-ok-linux-gnu/8.3.0/../../../../x86_64-ok-linux-gnu/bin/ld: /home/jmp/rpmbuild/BUILD/mate-session-manager-1.22.0/mate-session/gsm-systemd.c:464: undefined reference to `sd_session_get_type'
collect2: error: ld returned 1 exit status
     mate-session 1.22.0
              ===================

        prefix:                   /usr
        exec_prefix:              /usr
        libdir:                   /usr/lib64
        bindir:                   ${exec_prefix}/bin
        sbindir:                  /usr/sbin
        sysconfdir:               /etc
        localstatedir:            ${prefix}/var
        datadir:                  /usr/share
        source code location:     .
        compiler:                 gcc
        cflags:                   -g -O2
        Maintainer mode:          yes
        Warn about deprecations:  no

        Default WM:               marco
        Systemd support:          no
        IPv6 support:             yes
        Backtrace support:        no
        XRender support:          yes
        XSync support:            yes
        XTest support:            yes
        Build documentation:      yes

Note: same build context  for 1.21.0, is BUILDING OK  I guess the systemd=no is not used with gsm-systemd.  (building WITHOUT systemd is mandatory for us)

**Comment by jmrcpn** [comment]
Ok, I extracted TODAY (Mars 11, 2019) the mate-session-manager FROM git, and the
1.22.0X is compiling properly.
May I suggest to tag an experimental Version within git  and have a tar available within github (this "bug" is rather meaningful, build defect!)

**Comment by vkareh** [comment]
Fixed by #192
